# -*- coding: utf-8 -*-
"""Superstore Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10nDFHKo_oOs07qwI6vCwc372OiGPHeeh
"""

!pip install shap

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv("/content/Sample - Superstore.csv",encoding='latin1')
dataset.head()

dataset.info()

dataset.describe()

dataset.isnull().sum().sum()

dataset.duplicated().sum()

dataset['Order Date']=pd.to_datetime(dataset['Order Date'])
dataset['Ship Date']=pd.to_datetime(dataset['Ship Date'])

print(dataset['Order Date'].dtype)
print(dataset['Ship Date'].dtype)

set_1=dataset[['Category','Region','Ship Mode','Segment']]
for u_col in set_1:
  print("Unique values in ",u_col)
  print(dataset[u_col].unique())
  print("-"*50)

set_1.nunique()

#List all numeric columns
numeric_columns=[]
for i in dataset:
  if(dataset[i].dtype=='int64' or dataset[i].dtype=='float64'):
    numeric_columns.append(i)

print("Numeric Columns:", numeric_columns)

for column in numeric_columns:
  plt.figure(figsize=(6, 4)) # Create a new figure for each box plot
  plt.boxplot(dataset[column])
  plt.title(f'Box Plot of {column}') # Add a title for clarity
  plt.ylabel('Value') # Add y-axis label
  plt.show() # Display each plot separately

dataset[['Sales', 'Profit', 'Discount', 'Quantity']].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(dataset[['Sales', 'Profit', 'Discount', 'Quantity']].corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix Heatmap')
plt.show()

dataset['Profit Margin in %']=(dataset['Profit']/dataset['Sales'])*100

dataset['Profit Margin in %'].describe()

dataset.head()

import plotly.express as px
#Why Plotly?

# Unlike Matplotlib, Plotly creates:

# Interactive graphs
# Zooming
# Hover tooltips
# Better dashboards (especially with Streamlit)

# That's why it's a great choice for your AI dashboard.

monthly= dataset.groupby(dataset['Order Date'].dt.to_period('M'))
monthly_sales=monthly['Sales'].sum().reset_index()
monthly_sales['Order Date']=monthly_sales['Order Date'].astype(str)## Convert the Period datatype to string because Plotly does not directly support pandas Period objects.
monthly_sales

fig=px.line(monthly_sales,x='Order Date',y='Sales',title='Monthly Sales')
fig.show()

#SALES BY REGION

regional=dataset.groupby('Region')['Sales'].sum().reset_index()
regional

fig=px.bar(regional,x='Region',y='Sales',title='Sales by Region')
fig.show()

#Discount V/S Profit Scatter
trend=px.scatter(x=dataset['Discount'],y=dataset['Profit'],title='Discount V/S Profit')
trend.show()

"""Feature Engineering"""

dataset['Month']=dataset['Order Date'].dt.month
dataset['Year']=dataset['Order Date'].dt.year
dataset['Quarter']=dataset['Order Date'].dt.quarter

Features=['Month','Year','Quarter','Discount','Region','Category','Segment']
Target=['Sales']

X=dataset[Features]
y=dataset[Target]

print(X.shape)
print(y.shape)
print(X.head())

# Predicting monthly level sales
monthly=dataset.groupby(['Year','Month','Quarter','Region','Category'])['Sales'].sum().reset_index()
print(monthly.shape)
monthly.head()

X2=monthly[['Year','Month','Quarter','Region','Category']]
y2=monthly[['Sales']]

"""Now to incorporate Random Forest in this we need to encode the cayegorical variables . Choosing label encoding"""

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
X=X.copy()
for COL in ['Region','Category']:
  X[COL]=le.fit_transform(X[COL])

X.head()

"""Model Building"""

from sklearn.model_selection import train_test_split
X2_train,X2_test,y2_train,y2_test=train_test_split(X2,y2,test_size=0.2,random_state=42)
print(f"Shape of X_train: {X2_train.shape}")
print(f"Shape of X_test: {X2_test.shape}")

from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder instance
le = LabelEncoder()
rf_model=RandomForestRegressor
# Apply Label Encoding to the categorical columns in X2
X2_encoded = X2.copy()
for col in ['Region', 'Category']:
  X2_encoded[col] = le.fit_transform(X2_encoded[col])

# Split the encoded data into training and testing sets
X2_train, X2_test, y2_train, y2_test = train_test_split(X2_encoded, y2, test_size=0.2, random_state=42)


model2=rf_model(n_estimators=100,random_state=42)
model2.fit(X2_train,y2_train.values.ravel())
print("Model trained Successfully")

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
y_pred=model2.predict(X2_test)
y2_pred=model2.predict(X2_test)
mae2=mean_absolute_error(y2_test,y2_pred)
mse2=mean_squared_error(y2_test,y2_pred)
rmse2=np.sqrt(mse2)
r2_2=r2_score(y2_test,y2_pred)
print(f"MAE: {mae2:.2f}")
print(f"MSE: {mse2:.2f}")
print(f"RMSE: {rmse2:.2f}")
print(f"R2_Score: {r2_2:.2f}")

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X2_train,y2_train)

y_lr_pred=lr.predict(X2_test)
r2_lr=r2_score(y2_test,y_lr_pred)
print(f"R2_Score: {r2_lr:.2f}")

"""**KMeans Customer Segmentation on RFM features**"""

import datetime

reference_date = dataset['Order Date'].max() + pd.Timedelta(days=1)

rfm = dataset.groupby('Customer Name').agg({
    'Order Date': lambda x: (reference_date - x.max()).days,
    'Order ID': 'nunique',
    'Sales': 'sum'
}).reset_index()

rfm.columns = ['Customer Name', 'Recency', 'Frequency', 'Monetary']
rfm.head()

import numpy as np
from sklearn.preprocessing import StandardScaler

# Check skewness first
print(rfm[['Recency', 'Frequency', 'Monetary']].skew())

# Log transform to reduce skew (add 1 to avoid log(0) issues)
rfm['Recency_log'] = np.log1p(rfm['Recency'])
rfm['Frequency_log'] = np.log1p(rfm['Frequency'])
rfm['Monetary_log'] = np.log1p(rfm['Monetary'])

# Scale the log-transformed features
scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm[['Recency_log', 'Frequency_log', 'Monetary_log']])

rfm_scaled = pd.DataFrame(rfm_scaled, columns=['Recency_scaled', 'Frequency_scaled', 'Monetary_scaled'])

import numpy as np
from sklearn.preprocessing import StandardScaler

# Log transform only Recency and Monetary (Frequency skew is already low)
rfm['Recency_log'] = np.log1p(rfm['Recency'])
rfm['Monetary_log'] = np.log1p(rfm['Monetary'])

# Scale: log-transformed Recency & Monetary, raw Frequency
scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm[['Recency_log', 'Frequency', 'Monetary_log']])

rfm_scaled = pd.DataFrame(rfm_scaled, columns=['Recency_scaled', 'Frequency_scaled', 'Monetary_scaled'])
rfm_scaled.describe()

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

inertia = []
silhouette_scores = []
k_range = range(2, 11)

for k in k_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(rfm_scaled)
    inertia.append(km.inertia_)
    silhouette_scores.append(silhouette_score(rfm_scaled, labels))

# Elbow plot
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.plot(k_range, inertia, marker='o')
plt.xlabel('k')
plt.ylabel('Inertia')
plt.title('Elbow Method')

plt.subplot(1, 2, 2)
plt.plot(k_range, silhouette_scores, marker='o', color='orange')
plt.xlabel('k')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Score')

plt.tight_layout()
plt.show()

print(list(zip(k_range, silhouette_scores)))

kmeans_final = KMeans(n_clusters=4, random_state=42, n_init=10)
rfm['Cluster'] = kmeans_final.fit_predict(rfm_scaled)

# Check cluster sizes and average RFM per cluster
print(rfm['Cluster'].value_counts())
print(rfm.groupby('Cluster')[['Recency', 'Frequency', 'Monetary']].mean())

cluster_labels = {
    3: 'Champions',
    0: 'Loyal High-Value',
    1: 'At-Risk',
    2: 'Lost/Churned'
}
rfm['Segment'] = rfm['Cluster'].map(cluster_labels)
print(rfm['Segment'].value_counts())

import plotly.express as px

fig = px.scatter_3d(
    rfm,
    x='Recency',
    y='Frequency',
    z='Monetary',
    color='Segment',
    hover_data=['Customer Name'],
    title='Customer Segmentation (RFM) - KMeans Clusters',
    opacity=0.7
)
fig.update_layout(width=900, height=700)
fig.show()

from sklearn.ensemble import IsolationForest

# Select features relevant to detecting anomalous transactions
iso_features = dataset[['Sales', 'Quantity', 'Discount', 'Profit']].copy()

# Fit Isolation Forest
iso_forest = IsolationForest(n_estimators=100, contamination=0.05, random_state=42)
dataset['Anomaly'] = iso_forest.fit_predict(iso_features)

# -1 = anomaly, 1 = normal
print(dataset['Anomaly'].value_counts())

# Inspect the flagged anomalies
anomalies = dataset[dataset['Anomaly'] == -1]
print(anomalies[['Order ID', 'Sales', 'Quantity', 'Discount', 'Profit']].sort_values('Profit').head(10))

print(anomalies[['Order ID', 'Sales', 'Quantity', 'Discount', 'Profit']].sort_values('Profit', ascending=False).head(10))

import plotly.express as px

fig = px.scatter(
    dataset,
    x='Discount',
    y='Profit',
    color=dataset['Anomaly'].map({1: 'Normal', -1: 'Anomaly'}),
    hover_data=['Order ID', 'Sales', 'Quantity'],
    title='Transaction Anomaly Detection (Isolation Forest): Discount vs Profit',
    opacity=0.6,
    color_discrete_map={'Normal': 'lightblue', 'Anomaly': 'red'}
)
fig.update_layout(width=900, height=600)
fig.show()

import shap

# Replace with your actual Module 4 variable names if different
explainer = shap.TreeExplainer(model2)
shap_values = explainer.shap_values(X2_test)

# Summary plot - shows which features drive forecasts most, and direction of impact
shap.summary_plot(shap_values, X2_test)

print(X2_test.columns.tolist())

# Explain the anomaly score (decision_function), not predict_ or predict()
iso_explainer = shap.TreeExplainer(iso_forest)
iso_shap_values = iso_explainer.shap_values(iso_features)

shap.summary_plot(iso_shap_values, iso_features)

!pip install -q -U google-genai

from google import genai
from google.colab import userdata

api_key = userdata.get('GEMINI_API_KEY')
client = genai.Client(api_key=api_key)

response = client.models.generate_content(
    model='gemini-flash-latest',
    contents='Say hello and confirm you are working.'
)
print(response.text)

import numpy as np

# Dynamic segment summary (Module 5 output)
segment_summary = rfm.groupby('Segment').agg(
    count=('Segment', 'count'),
    avg_recency=('Recency', 'mean'),
    avg_frequency=('Frequency', 'mean'),
    avg_monetary=('Monetary', 'mean')
).round(1).to_dict('index')

# Dynamic anomaly summary (Module 6 output)
anomaly_count = int((dataset['Anomaly'] == -1).sum())
anomaly_pct = round(anomaly_count / len(dataset) * 100, 1)

# Dynamic SHAP top drivers (Module 7 output)
top_feature_rf = X2_test.columns[np.argmax(np.abs(shap_values).mean(axis=0))]
top_feature_iso = iso_features.columns[np.argmax(np.abs(iso_shap_values).mean(axis=0))]

findings_summary = f"""
RETAIL INTELLIGENCE DASHBOARD - KEY FINDINGS

1. Customer Segmentation (RFM, KMeans k=4): {segment_summary}

2. Anomaly Detection (Isolation Forest): {anomaly_count} transactions ({anomaly_pct}%) flagged as unusual.

3. SHAP Explainability:
   - Sales forecasting top driver: {top_feature_rf}
   - Anomaly detection top driver: {top_feature_iso}
"""

print(findings_summary)

prompt = f"""
You are a retail business analyst reviewing findings from a data science project on a superstore dataset.

{findings_summary}

Write a two-part response:

PART 1 - KEY INSIGHTS
Explain what each finding actually means for the business in plain terms (not restating the numbers, but interpreting them). 3-4 insights, 1-2 sentences each.

PART 2 - RECOMMENDATIONS
Based on those insights, give 4 concise, actionable recommendations a retail manager could act on.
Each should reference the specific finding it's based on, suggest a concrete action, and be 1-2 sentences.

Professional but approachable tone, no jargon. Use clear headers for each part.
"""

response = client.models.generate_content(
    model='gemini-flash-latest',
    contents=prompt
)
print(response.text)

knowledge_base = [
    "Discount-Profitability: Profit turns negative when discount exceeds approximately 20%. Validated via scatter analysis and confirmed by anomaly detection.",
    f"Customer Segmentation (KMeans RFM, k=4): {segment_summary}",
    f"Anomaly Detection: {anomaly_count} transactions ({anomaly_pct}%) flagged by Isolation Forest. Two tails identified — deep-loss (high discount + negative profit) and high-profit (zero discount, large B2B orders).",
    f"SHAP Explainability: Sales forecasting top driver is {top_feature_rf} (seasonality). Anomaly detection top driver is {top_feature_iso}.",
    "Sales Forecasting: Random Forest achieved R2 = 0.11, indicating retail sales variance requires external signals (promotions, macroeconomic data) for production-grade accuracy.",
    "EDA Finding: Zero nulls and zero duplicates in the dataset. IQR outlier removal was rejected — high-value B2B orders are legitimate, not errors."
]

print(f"Knowledge base has {len(knowledge_base)} chunks")

import numpy as np

# Embed each chunk in the knowledge base using Gemini's embedding model
def embed_text(text):
    result = client.models.embed_content(
        model='gemini-embedding-001',
        contents=text
    )
    return np.array(result.embeddings[0].values)

kb_embeddings = np.array([embed_text(chunk) for chunk in knowledge_base])
print(f"Embedded {kb_embeddings.shape[0]} chunks, each with {kb_embeddings.shape[1]} dimensions")

# Retrieval: cosine similarity between query and knowledge base
def retrieve(query, top_k=2):
    query_embedding = embed_text(query)
    similarities = np.dot(kb_embeddings, query_embedding) / (
        np.linalg.norm(kb_embeddings, axis=1) * np.linalg.norm(query_embedding)
    )
    top_indices = np.argsort(similarities)[::-1][:top_k]
    return [knowledge_base[i] for i in top_indices]

# Quick test
test_results = retrieve("why are some transactions flagged as unusual?")
print(test_results)

def rag_answer(query, top_k=2):
    retrieved_chunks = retrieve(query, top_k=top_k)
    context = "\n".join(retrieved_chunks)

    prompt = f"""
You are a retail business analyst. Answer the user's question using ONLY the context below.
If the context doesn't contain enough information, say so honestly rather than guessing.

Context:
{context}

Question: {query}

Answer in 2-3 sentences, referencing specific numbers from the context where relevant.
"""

    response = client.models.generate_content(
        model='gemini-flash-latest',
        contents=prompt
    )
    return response.text

# Test it
print(rag_answer("Why are some transactions flagged as unusual?"))
print("\n---\n")
print(rag_answer("What did SHAP reveal about the sales forecasting model?"))

expected_roles = {
    "order_date": "Date the order was placed",
    "ship_date": "Date the order was shipped",
    "customer_id": "Unique customer identifier or name",
    "sales": "Revenue amount for the transaction",
    "profit": "Profit amount for the transaction",
    "discount": "Discount applied, as a decimal or percentage",
    "quantity": "Number of units ordered",
    "region": "Geographic region of the order",
    "category": "Product category"
}

actual_columns = dataset.columns.tolist()

mapping_prompt = f"""
You are matching column names from a retail dataset to a set of expected roles.

Actual columns in the dataset: {actual_columns}

Expected roles and their meanings:
{expected_roles}

Return ONLY a valid JSON object mapping each role to the best-matching actual column name.
If no good match exists for a role, use null.
Example format: {{"order_date": "Order Date", "sales": "Sales", ...}}
No explanation, no markdown, just the JSON.
"""

response = client.models.generate_content(
    model='gemini-flash-latest',
    contents=mapping_prompt
)

import json
column_mapping = json.loads(response.text.strip().strip('```json').strip('```'))
print(column_mapping)

test_dataset = dataset.rename(columns={
    'Order Date': 'order dt',
    'Profit': 'Total Profit ($)',
    'Sales': 'Revenue',
    'Customer Name': 'Client'
})

test_prompt = mapping_prompt.replace(str(actual_columns), str(test_dataset.columns.tolist()))

response = client.models.generate_content(
    model='gemini-flash-latest',
    contents=test_prompt
)
print(response.text)